version: "3.8"
name: wf-emulator
services:
    wf.server:
        container_name: wf.server
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../..:/workspaces:cached

        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity

        depends_on:
            - wf.database

        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:wf.database

        # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

    wf.database:
        image: mongo:latest
        container_name: wf.database
        restart: unless-stopped
        volumes:
            - mongodb-data:/data/db

        # Uncomment to change startup options
        # environment:
        #  MONGO_INITDB_ROOT_USERNAME: root
        #  MONGO_INITDB_ROOT_PASSWORD: example
        #  MONGO_INITDB_DATABASE: your-database-here

        # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
    mongodb-data:
