name: Prettier
on: [push]
jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  ref: ${{ github.head_ref }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.x"
            - run: npm ci
            - run: npm run prettier
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5.0.0
              with:
                  commit_message: Apply prettier changes
                  branch: ${{ github.head_ref }}
